### ISSUE TITLE
getNames is not working with react

### ISSUE THREAD

**Issue by Priya-dev** [michaelwittig/node-i18n-iso-countries#263]
I am new here and I am trying to populate the dropdown for countries. 
The log shows an empty object. Am I missing something here

```
import countries from 'i18n-iso-countries';

  console.log(countries.getNames('en', { select: 'official' })); // {}
```

**Comment by korbav** [comment]
Hi @Priya-dev ,

It actually does work well, at least in React 17.0.2 : 
![image](https://user-images.githubusercontent.com/6184386/140445173-cebbe5c3-e475-4cae-9ff4-0f8d129b02d7.png)

I'm almost sure you forgot to register the 'en' locale beforehand: `countries.registerLocale(require('i18n-iso-countries/langs/en.json'));`

If registering the 'en' language doesn't give any positive outcome, please elaborate on which React version you're using, and maybe create a codesandebox repo so that we can try it out 👍

**Comment by Priya-dev** [comment]
Yes, @korbav. That worked!! Thanks for your time.  

```
import countries from 'i18n-iso-countries';
import english from "i18n-iso-countries/langs/en.json";

  countries.registerLocale(english);
  console.log(countries.getNames('en', { select: 'official' }));  // gives list of countries
```
