### ISSUE TITLE
Getting compiling warning with v3.7.0

### ISSUE THREAD

**Issue by AugustusZ** [michaelwittig/node-i18n-iso-countries#98]
Getting this warning since updated to 3.7.0:

```
Compiled with warnings.

./node_modules/i18n-iso-countries/index.js
46:18-63 Critical dependency: the request of a dependency is an expression
```

Is there a way to ignore this warning? Thanks!

**Comment by michaelwittig** [comment]
The only change from 3.6.3 3.7.0 was this: https://github.com/michaelwittig/node-i18n-iso-countries/commit/060eab6957f78534e7f1fe1b4fc7f734d8e2e474#diff-168726dbe96b3ce427e7fedce31bb0bc

Is import a reserved word or something? @ExNG

**Comment by ExNG** [comment]
Thats not the case.

When registering a locale the user needs to require a json file which would've been done outside the lib, but i suggested a change thta would move this into the lib.
See:

```javascript
let localData = require(['./langs/', code, '.json'].join(''));
```

now Uglify tries to bundle this require but cant because of the parameter being evaluated in the runtime. A possible fix for that warning would be to require all json and then register the one wished, which would no doubt destroy the whole purpose of registering a locale and of course increase the overall filesize and memory weight when used.

**Comment by michaelwittig** [comment]
so the issue title should be that UglifyJs does not work with the way we import languages?

**Comment by michaelwittig** [comment]
I reverted the change the was likely the cause of this.

Please use `i18n-iso-countries@3.7.3`
